# -------------------------------
# Global parameters
# -------------------------------

# Number of threads to use
threads: 32

# Input FASTA directory (with .fa/.fasta/.fna files named by sample)
data_dir: "/home/bradd.mendoza/plaswrapv1/data"

# Output directory
output_dir: "/home/bradd.mendoza/plaswrapv1/results"

# Where all tool databases are stored
db_root: "/home/bradd.mendoza/plaswrapv1/dbs"

# -------------------------------
# Mode selection
#   balance   = platon Accuracy
#   precision = platon specificity
# -------------------------------
mode: "balance"

# -------------------------------
# Tool toggles (enable/disable)
# -------------------------------
run_tools:
  plasx: true
  platon: true
  plasmidhunter: true
  plasclass: true

# -------------------------------
# Tool-specific parameters
# -------------------------------

#anvio:
#  conda_env: "anvio-8"
#  cog_version: "COG20"
#  cog_data_dir: "db/Anvio/COG20"
#  pfam_data_dir: "db/Anvio/Pfam-37.4"

#platon:
#  db: "db/platon"

#plasx:
#  conda_env: "plasx"

